import { ButtonCardDataProps } from '../../../../type/index';

export const cardData: ButtonCardDataProps[] = [
  {
    heading: 'デザイン1',
    styleObj: {
      display: 'display: inline-block;',
      textDecoration: 'text-decoration: none;',
      padding: 'padding: 4px 12px;',
      fontSize: 'font-size: 16px;',
      background: 'background: #fff;',
      color: 'color: #67c5ff;',
      border: 'border: 2px solid #67c5ff;',
      borderRadius: 'border-radius: 3px;',
      transition: 'transition: .4s;',
    },
    hoverStyle: {
      background: 'background: #67c5ff;',
      color: 'color: #fff;',
    },
    customStyle: {
      paddingX: '4',
      paddingY: '12',
      borderRadius: '3',
      background: '#fff',
      color: '#67c5ff',
    },
  },
  {
    heading: 'デザイン2',
    styleObj: {
      display: 'display: inline-block;',
      textDecoration: 'text-decoration: none;',
      padding: 'padding: 4px 12px;',
      fontSize: 'font-size: 16px;',
      background: 'background: #fff;',
      color: 'color: #67c5ff;',
      border: 'border: 2px solid #67c5ff;',
      transition: 'transition: .4s;',
    },
    hoverStyle: {
      background: 'background: #67c5ff;',
      color: 'color: #fff;',
    },
    customStyle: {
      paddingX: '4',
      paddingY: '12',
      borderRadius: '0',
      background: '#fff',
      color: '#67c5ff',
    },
  },
  {
    heading: 'デザイン3',
    styleObj: {
      display: 'display: inline-block;',
      textDecoration: 'text-decoration: none;',
      padding: 'padding: 4px 12px;',
      fontSize: 'font-size: 16px;',
      background: 'background: #46b574;',
      color: 'color: #fff;',
      borderBottom: 'border-bottom: 4px solid #12614d;',
      borderRadius: 'border-radius: 3px;',
    },
    activeStyle: {
      transform: 'transform: translateY(4px);',
      borderBottom: 'border-bottom: none;',
    },
    customStyle: {
      paddingX: '4',
      paddingY: '12',
      borderRadius: '3',
      background: '#46b574',
      color: '#fff',
    },
  },
  {
    heading: 'デザイン4',
    styleObj: {
      display: 'display: inline-block;',
      textDecoration: 'text-decoration: none;',
      padding: 'padding: 4px 12px;',
      fontSize: 'font-size: 16px;',
      background: 'background: #46b574;',
      color: 'color: #fff;',
      borderBottom: 'border-bottom: 4px solid #12614d;',
    },
    activeStyle: {
      transform: 'transform: translateY(4px);',
      borderBottom: 'border-bottom: none;',
    },
    customStyle: {
      paddingX: '4',
      paddingY: '12',
      borderRadius: '0',
      background: '#46b574',
      color: '#fff',
    },
  },
  {
    heading: 'デザイン5',
    styleObj: {
      display: 'display: inline-block;',
      textDecoration: 'text-decoration: none;',
      padding: 'padding: 4px 12px;',
      fontSize: 'font-size: 16px;',
      background: 'background: #fff;',
      border: 'border: 4px double orange;',
      borderRadius: 'border-radius: 3px;',
      transition: 'transition: .4s;',
    },
    customStyle: {
      paddingX: '4',
      paddingY: '12',
      borderRadius: '3',
      background: '#fff',
      color: '#000',
    },
  },
  {
    heading: 'デザイン6',
    styleObj: {
      display: 'display: inline-block;',
      textDecoration: 'text-decoration: none;',
      padding: 'padding: 4px 12px;',
      fontSize: 'font-size: 16px;',
      fontWeight: 'font-weight: bold;',
      background: 'background: #ffecb3;',
      color: 'color: orange;',
      borderLeft: 'border-left: 4px solid orange;',
      borderRight: 'border-right: 4px solid orange;',
      transition: 'transition: .4s;',
    },
    hoverStyle: {
      background: 'background: orange;',
      color: 'color: #fff;',
    },
    customStyle: {
      paddingX: '4',
      paddingY: '12',
      borderRadius: '0',
      background: '#ffecb3',
      color: '#ffa500',
    },
  },
  {
    heading: 'デザイン7',
    styleObj: {
      display: 'display: inline-block;',
      textDecoration: 'text-decoration: none;',
      padding: 'padding: 4px 12px;',
      fontSize: 'font-size: 16px;',
      background: 'background: #0069eb;',
      color: 'color: #fff;',
      borderRadius: 'border-radius: 30px;',
    },
    customStyle: {
      paddingX: '4',
      paddingY: '12',
      borderRadius: '30',
      background: '#0069eb',
      color: '#fff',
    },
  },
  {
    heading: 'デザイン8',
    styleObj: {
      display: 'display: inline-block;',
      textDecoration: 'text-decoration: none;',
      padding: 'padding: 4px 12px;',
      fontSize: 'font-size: 16px;',
      fontWeight: 'font-weight: bold;',
      background: 'background: #e4f0ff;',
      color: 'color: #0069eb;',
      border: 'border: 2px dashed #67c5ff;',
    },
    customStyle: {
      paddingX: '4',
      paddingY: '12',
      borderRadius: '0',
      background: '#e4f0ff',
      color: '#0069eb',
    },
  },
];
